
name: Video tracker publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: install dependencies
        run: dotnet resotre ./backend.csproj

      - name: build
        run: dotnet build ./backend.csproj --configuration Release --no-restore

      - name: publish
        run: dotnet publish ./backend.csproj --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write 

    steps:
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'video-tracker'
          publish-profile: ${{secrets.AZURE_PUBLISH_PROFILE}}
          slot-name: 'production'
          package: './publish'
